package com.cosmere.registry;

import java.util.EnumMap;
import java.util.Map;

import com.cosmere.Cosmere;
import com.cosmere.block.HemalurgicTableBlock;
import com.cosmere.block.MetallurgyTableBlock;
import com.cosmere.metal.Metal;
import com.cosmere.metal.Mineral;

import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * Every block the mod adds. Ores and storage blocks are generated by walking {@link Metal}
 * and {@link Mineral} so a new metal never needs a hand-written registration here.
 */
public final class ModBlocks {
    public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(Cosmere.MODID);

    /** Stone-hosted ores, keyed by metal. Only metals with {@link Metal.Source#ORE}. */
    public static final Map<Metal, DeferredBlock<Block>> METAL_ORES = new EnumMap<>(Metal.class);
    public static final Map<Metal, DeferredBlock<Block>> DEEPSLATE_METAL_ORES = new EnumMap<>(Metal.class);
    /** Full storage blocks for every metal the mod supplies ingots for. */
    public static final Map<Metal, DeferredBlock<Block>> METAL_BLOCKS = new EnumMap<>(Metal.class);

    public static final Map<Mineral, DeferredBlock<Block>> MINERAL_ORES = new EnumMap<>(Mineral.class);
    public static final Map<Mineral, DeferredBlock<Block>> DEEPSLATE_MINERAL_ORES = new EnumMap<>(Mineral.class);
    public static final Map<Mineral, DeferredBlock<Block>> MINERAL_BLOCKS = new EnumMap<>(Mineral.class);

    public static final DeferredBlock<MetallurgyTableBlock> METALLURGY_TABLE = BLOCKS.registerBlock(
            "metallurgy_table",
            MetallurgyTableBlock::new,
            BlockBehaviour.Properties.of()
                    .mapColor(MapColor.METAL)
                    .strength(3.5F, 6.0F)
                    .requiresCorrectToolForDrops()
                    .sound(SoundType.METAL));

    public static final DeferredBlock<HemalurgicTableBlock> HEMALURGIC_TABLE = BLOCKS.registerBlock(
            "hemalurgic_table",
            HemalurgicTableBlock::new,
            BlockBehaviour.Properties.of()
                    .mapColor(MapColor.STONE)
                    .strength(2.0F, 6.0F)
                    .requiresCorrectToolForDrops()
                    .sound(SoundType.STONE)
                    .noOcclusion());

    static {
        for (Metal metal : Metal.values()) {
            if (metal.hasOwnOre()) {
                // Atium is buried with the Pits of Hathsin; give it deepslate-only, richer XP.
                boolean deepOnly = metal == Metal.ATIUM;
                if (!deepOnly) {
                    METAL_ORES.put(metal, BLOCKS.registerBlock(
                            metal.id() + "_ore",
                            props -> new DropExperienceBlock(oreXp(metal), props),
                            oreProperties(false)));
                }
                DEEPSLATE_METAL_ORES.put(metal, BLOCKS.registerBlock(
                        "deepslate_" + metal.id() + "_ore",
                        props -> new DropExperienceBlock(oreXp(metal), props),
                        oreProperties(true)));
            }
            if (metal.hasOwnIngot()) {
                METAL_BLOCKS.put(metal, BLOCKS.registerSimpleBlock(
                        metal.id() + "_block",
                        storageProperties()));
            }
        }

        for (Mineral mineral : Mineral.values()) {
            MINERAL_ORES.put(mineral, BLOCKS.registerBlock(
                    mineral.id() + "_ore",
                    props -> new DropExperienceBlock(UniformInt.of(0, 2), props),
                    oreProperties(false)));
            DEEPSLATE_MINERAL_ORES.put(mineral, BLOCKS.registerBlock(
                    "deepslate_" + mineral.id() + "_ore",
                    props -> new DropExperienceBlock(UniformInt.of(0, 2), props),
                    oreProperties(true)));
            MINERAL_BLOCKS.put(mineral, BLOCKS.registerSimpleBlock(
                    mineral.id() + "_block",
                    storageProperties()));
        }
    }

    private static UniformInt oreXp(Metal metal) {
        return metal.isGodMetal() ? UniformInt.of(5, 12) : UniformInt.of(0, 2);
    }

    private static BlockBehaviour.Properties oreProperties(boolean deepslate) {
        BlockBehaviour.Properties props = BlockBehaviour.Properties.ofFullCopy(deepslate ? Blocks.DEEPSLATE_IRON_ORE : Blocks.IRON_ORE);
        return props.requiresCorrectToolForDrops();
    }

    private static BlockBehaviour.Properties storageProperties() {
        return BlockBehaviour.Properties.of()
                .mapColor(MapColor.METAL)
                .strength(5.0F, 6.0F)
                .requiresCorrectToolForDrops()
                .sound(SoundType.METAL);
    }

    private ModBlocks() {
    }
}
