package com.cosmere.registry;

import java.util.EnumMap;
import java.util.Map;

import com.cosmere.Cosmere;
import com.cosmere.item.BlindfoldItem;
import com.cosmere.item.CoinItem;
import com.cosmere.item.DaggerItem;
import com.cosmere.item.KolossSkinItem;
import com.cosmere.item.LerasiumBeadItem;
import com.cosmere.item.MetalVialItem;
import com.cosmere.item.MetalmindItem;
import com.cosmere.item.ModTiers;
import com.cosmere.item.SpikeItem;
import com.cosmere.item.SpikeJarItem;
import com.cosmere.metal.Metal;
import com.cosmere.metal.Mineral;

import net.minecraft.world.item.AxeItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.SwordItem;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * Every item the mod adds.
 *
 * <p>The bulk of it is generated by walking {@link Metal} and {@link Mineral}: each metal gets
 * an ingot, a nugget, a vial, a spike, a ring and a bracer, plus a raw drop where it has its
 * own ore. Adding a metal to the enum adds all of them.
 */
public final class ModItems {
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(Cosmere.MODID);

    public static final Map<Metal, DeferredItem<Item>> INGOTS = new EnumMap<>(Metal.class);
    public static final Map<Metal, DeferredItem<Item>> NUGGETS = new EnumMap<>(Metal.class);
    public static final Map<Metal, DeferredItem<Item>> RAW_METALS = new EnumMap<>(Metal.class);
    public static final Map<Metal, DeferredItem<MetalVialItem>> VIALS = new EnumMap<>(Metal.class);
    public static final Map<Metal, DeferredItem<SpikeItem>> SPIKES = new EnumMap<>(Metal.class);
    public static final Map<Metal, DeferredItem<MetalmindItem>> RINGS = new EnumMap<>(Metal.class);
    public static final Map<Metal, DeferredItem<MetalmindItem>> BRACERS = new EnumMap<>(Metal.class);

    public static final Map<Mineral, DeferredItem<Item>> MINERAL_INGOTS = new EnumMap<>(Mineral.class);
    public static final Map<Mineral, DeferredItem<Item>> MINERAL_NUGGETS = new EnumMap<>(Mineral.class);
    public static final Map<Mineral, DeferredItem<Item>> RAW_MINERALS = new EnumMap<>(Mineral.class);

    // --- currency ---
    public static final DeferredItem<CoinItem> CLIP = ITEMS.register("clip",
            () -> new CoinItem(1, new Item.Properties()));
    public static final DeferredItem<CoinItem> BOXING = ITEMS.register("boxing",
            () -> new CoinItem(8, new Item.Properties()));

    // --- gear ---
    public static final DeferredItem<BlindfoldItem> BLINDFOLD = ITEMS.register("blindfold",
            () -> new BlindfoldItem(new Item.Properties().stacksTo(1).durability(0)));
    public static final DeferredItem<SpikeJarItem> SPIKE_JAR = ITEMS.register("spike_jar",
            () -> new SpikeJarItem(new Item.Properties()));
    public static final DeferredItem<KolossSkinItem> KOLOSS_SKIN = ITEMS.register("koloss_skin",
            () -> new KolossSkinItem(new Item.Properties()));
    public static final DeferredItem<LerasiumBeadItem> LERASIUM_BEAD = ITEMS.register("lerasium_bead",
            () -> new LerasiumBeadItem(new Item.Properties()));
    public static final DeferredItem<Item> ATIUM_BEAD = ITEMS.register("atium_bead",
            () -> new Item(new Item.Properties().rarity(Rarity.RARE)));

    // --- weapons ---
    // Glass and obsidian cannot be Pushed or Pulled, which is the entire point of carrying them.
    public static final DeferredItem<DaggerItem> GLASS_DAGGER = ITEMS.register("glass_dagger",
            () -> new DaggerItem(ModTiers.GLASS, DaggerItem.properties(ModTiers.GLASS)));
    public static final DeferredItem<SwordItem> GLASS_SWORD = ITEMS.register("glass_sword",
            () -> new SwordItem(ModTiers.GLASS, new Item.Properties()
                    .attributes(SwordItem.createAttributes(ModTiers.GLASS, 3, -2.4F))));
    public static final DeferredItem<DaggerItem> OBSIDIAN_DAGGER = ITEMS.register("obsidian_dagger",
            () -> new DaggerItem(ModTiers.OBSIDIAN, DaggerItem.properties(ModTiers.OBSIDIAN)));
    public static final DeferredItem<SwordItem> OBSIDIAN_SWORD = ITEMS.register("obsidian_sword",
            () -> new SwordItem(ModTiers.OBSIDIAN, new Item.Properties()
                    .attributes(SwordItem.createAttributes(ModTiers.OBSIDIAN, 3, -2.4F))));
    public static final DeferredItem<AxeItem> OBSIDIAN_AXE = ITEMS.register("obsidian_axe",
            () -> new AxeItem(ModTiers.OBSIDIAN, new Item.Properties()
                    .attributes(AxeItem.createAttributes(ModTiers.OBSIDIAN, 6.0F, -3.1F))));
    public static final DeferredItem<DaggerItem> STEEL_DAGGER = ITEMS.register("steel_dagger",
            () -> new DaggerItem(ModTiers.COSMERE_STEEL, DaggerItem.properties(ModTiers.COSMERE_STEEL)));
    public static final DeferredItem<SwordItem> DUELING_CANE = ITEMS.register("dueling_cane",
            () -> new SwordItem(ModTiers.COSMERE_STEEL, new Item.Properties()
                    .attributes(SwordItem.createAttributes(ModTiers.COSMERE_STEEL, 2, -2.0F))));

    // --- spawn eggs ---
    public static final DeferredItem<DeferredSpawnEggItem> MISTWRAITH_SPAWN_EGG = ITEMS.register("mistwraith_spawn_egg",
            () -> new DeferredSpawnEggItem(ModEntities.MISTWRAITH, 0xBFC4C8, 0x6E5F52, new Item.Properties()));
    public static final DeferredItem<DeferredSpawnEggItem> KANDRA_SPAWN_EGG = ITEMS.register("kandra_spawn_egg",
            () -> new DeferredSpawnEggItem(ModEntities.KANDRA, 0xE0D3B8, 0x8C6A4A, new Item.Properties()));
    public static final DeferredItem<DeferredSpawnEggItem> KOLOSS_SPAWN_EGG = ITEMS.register("koloss_spawn_egg",
            () -> new DeferredSpawnEggItem(ModEntities.KOLOSS, 0x3B6FA0, 0x1E3F5C, new Item.Properties()));
    public static final DeferredItem<DeferredSpawnEggItem> WOLFHOUND_SPAWN_EGG = ITEMS.register("wolfhound_spawn_egg",
            () -> new DeferredSpawnEggItem(ModEntities.WOLFHOUND, 0x5A4B3C, 0x2E2620, new Item.Properties()));

    static {
        registerMetalItems();
        registerMineralItems();
        registerBlockItems();
    }

    private static void registerMetalItems() {
        for (Metal metal : Metal.values()) {
            Rarity rarity = metal.isGodMetal() ? Rarity.RARE : Rarity.COMMON;

            if (metal.hasOwnIngot()) {
                INGOTS.put(metal, ITEMS.registerSimpleItem(metal.id() + "_ingot", new Item.Properties().rarity(rarity)));
            }
            if (metal.hasOwnNugget()) {
                NUGGETS.put(metal, ITEMS.registerSimpleItem(metal.id() + "_nugget", new Item.Properties().rarity(rarity)));
            }
            if (metal.hasOwnOre()) {
                RAW_METALS.put(metal, ITEMS.registerSimpleItem("raw_" + metal.id(), new Item.Properties().rarity(rarity)));
            }
            if (metal != Metal.LERASIUM) {
                // Lerasium is never drunk in flakes; it comes as a bead and is swallowed whole.
                VIALS.put(metal, ITEMS.register(metal.id() + "_vial",
                        () -> new MetalVialItem(metal, new Item.Properties().stacksTo(16).rarity(rarity))));
            }
            SPIKES.put(metal, ITEMS.register(metal.id() + "_spike",
                    () -> new SpikeItem(metal, new Item.Properties().stacksTo(16).rarity(rarity))));
            RINGS.put(metal, ITEMS.register(metal.id() + "_ring",
                    () -> new MetalmindItem(metal, MetalmindItem.Form.RING, new Item.Properties().rarity(rarity))));
            BRACERS.put(metal, ITEMS.register(metal.id() + "_bracer",
                    () -> new MetalmindItem(metal, MetalmindItem.Form.BRACER, new Item.Properties().rarity(rarity))));
        }
    }

    private static void registerMineralItems() {
        for (Mineral mineral : Mineral.values()) {
            MINERAL_INGOTS.put(mineral, ITEMS.registerSimpleItem(mineral.id() + "_ingot", new Item.Properties()));
            MINERAL_NUGGETS.put(mineral, ITEMS.registerSimpleItem(mineral.id() + "_nugget", new Item.Properties()));
            RAW_MINERALS.put(mineral, ITEMS.registerSimpleItem("raw_" + mineral.id(), new Item.Properties()));
        }
    }

    private static void registerBlockItems() {
        ModBlocks.METAL_ORES.values().forEach(ITEMS::registerSimpleBlockItem);
        ModBlocks.DEEPSLATE_METAL_ORES.values().forEach(ITEMS::registerSimpleBlockItem);
        ModBlocks.METAL_BLOCKS.values().forEach(ITEMS::registerSimpleBlockItem);
        ModBlocks.MINERAL_ORES.values().forEach(ITEMS::registerSimpleBlockItem);
        ModBlocks.DEEPSLATE_MINERAL_ORES.values().forEach(ITEMS::registerSimpleBlockItem);
        ModBlocks.MINERAL_BLOCKS.values().forEach(ITEMS::registerSimpleBlockItem);
        ITEMS.registerSimpleBlockItem(ModBlocks.METALLURGY_TABLE);
        ITEMS.registerSimpleBlockItem(ModBlocks.HEMALURGIC_TABLE);
    }

    private ModItems() {
    }
}
